name: Feature request
description: Запит на нову функціональність
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes: { label: Проблема/потреба }
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes: { label: Запропоноване рішення }
    validations: { required: true }
  - type: textarea
    id: acceptance
    attributes: { label: Acceptance criteria, placeholder: "- Коли ..., маю бачити ...
- ..." }
    validations: { required: true }
  - type: dropdown
    id: priority
    attributes: { label: Пріоритет, options: [P0, P1, P2, P3] }
    validations: { required: true }
